title: Owen Elisa
description: my semi-professional, mostly personal, and definitely gay af web presence
url: "https://owen.radsectors.com"
lang: en_US
author: Owen Elisa
copyright: radsectors
email:

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag
